FROM python:3.11-slim

WORKDIR /app
COPY telegram_omdb_bot_service_client.py /app/
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# run the bot
ENV PYTHONUNBUFFERED=1
CMD ["python", "telegram_omdb_bot_service_client.py"]
