# Dockerfile.bot
FROM python:3.11-slim

# avoid prompts
ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# copy everything (source files + requirements)
COPY . /app

# install deps
RUN python -m pip install --upgrade pip \
 && pip install --no-cache-dir -r requirements.txt

# run bot
CMD ["python", "bot.py"]
